[book]
authors = ["zyansheep"]
language = "en"
multilingual = false
create-missing = false
src = "."
title = "Dither Ideas"

[build]
build-dir = "public/docs"

[output.html]
additional-css = ["custom.css"]

[preprocessor.katex]
after = ["links"]